// swift-tools-version: 6.0
import PackageDescription

// Umbrella package exposing the three HerdMan libraries as a single local
// Swift package, so the app links one package reference. Each target reuses the
// per-module folder layout under Packages/<Module>/.
let package = Package(
    name: "HerdManKit",
    platforms: [
        .macOS("26.0")
    ],
    products: [
        .library(name: "ACPKit", targets: ["ACPKit"]),
        .library(name: "StreamMarkdown", targets: ["StreamMarkdown"]),
        .library(name: "HerdManTheming", targets: ["HerdManTheming"]),
        .library(name: "CodeHighlighter", targets: ["CodeHighlighter"]),
        .library(name: "HerdManCore", targets: ["HerdManCore"])
    ],
    targets: [
        // MARK: HerdManTheming (VSCode/Shiki theme parsing, normalization,
        // palette derivation — Foundation-only, no SwiftUI)
        .target(
            name: "HerdManTheming",
            path: "HerdManTheming/Sources/HerdManTheming",
            resources: [.copy("Resources/Themes")],
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "HerdManThemingTests",
            dependencies: ["HerdManTheming"],
            path: "HerdManTheming/Tests/HerdManThemingTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),

        // MARK: ACPKit
        .target(
            name: "ACPKit",
            path: "ACPKit/Sources/ACPKit",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "ACPKitTests",
            dependencies: ["ACPKit"],
            path: "ACPKit/Tests/ACPKitTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),

        // MARK: StreamMarkdown
        .target(
            name: "StreamMarkdown",
            path: "StreamMarkdown/Sources/StreamMarkdown",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "StreamMarkdownTests",
            dependencies: ["StreamMarkdown"],
            path: "StreamMarkdown/Tests/StreamMarkdownTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),

        // MARK: CodeHighlighter (Shiki running in JavaScriptCore; the bundled
        // highlighter.js is generated by apps/macos/scripts/build-highlighter.mjs)
        .target(
            name: "CodeHighlighter",
            path: "CodeHighlighter/Sources/CodeHighlighter",
            resources: [.copy("Resources/highlighter.js")],
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "CodeHighlighterTests",
            dependencies: ["CodeHighlighter"],
            path: "CodeHighlighter/Tests/CodeHighlighterTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),

        // MARK: HerdManCore (app logic: models, repositories, DI, view models)
        .target(
            name: "HerdManCore",
            dependencies: ["ACPKit", "HerdManTheming"],
            path: "HerdManCore/Sources/HerdManCore",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "HerdManCoreTests",
            dependencies: ["HerdManCore", "ACPKit"],
            path: "HerdManCore/Tests/HerdManCoreTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        )
    ]
)
