// swift-tools-version: 6.0
import PackageDescription

// Umbrella package exposing the three Codevisor libraries as a single local
// Swift package, so the app links one package reference. Each target reuses the
// per-module folder layout under Packages/<Module>/.
let package = Package(
    name: "CodevisorKit",
    platforms: [
        .macOS("26.0")
    ],
    products: [
        .library(name: "ACPKit", targets: ["ACPKit"]),
        .library(name: "StreamMarkdown", targets: ["StreamMarkdown"]),
        .library(name: "CodevisorTheming", targets: ["CodevisorTheming"]),
        .library(name: "CodeHighlighter", targets: ["CodeHighlighter"]),
        .library(name: "CodevisorCore", targets: ["CodevisorCore"])
    ],
    dependencies: [
        .package(url: "https://github.com/PostHog/posthog-ios.git", exact: "3.59.3")
    ],
    targets: [
        // MARK: CodevisorTheming (VSCode/Shiki theme parsing, normalization,
        // palette derivation — Foundation-only, no SwiftUI)
        .target(
            name: "CodevisorTheming",
            path: "CodevisorTheming/Sources/CodevisorTheming",
            resources: [.copy("Resources/Themes")],
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "CodevisorThemingTests",
            dependencies: ["CodevisorTheming"],
            path: "CodevisorTheming/Tests/CodevisorThemingTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),

        // MARK: ACPKit
        .target(
            name: "ACPKit",
            path: "ACPKit/Sources/ACPKit",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "ACPKitTests",
            dependencies: ["ACPKit"],
            path: "ACPKit/Tests/ACPKitTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),

        // MARK: StreamMarkdown
        .target(
            name: "StreamMarkdown",
            path: "StreamMarkdown/Sources/StreamMarkdown",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "StreamMarkdownTests",
            dependencies: ["StreamMarkdown"],
            path: "StreamMarkdown/Tests/StreamMarkdownTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),

        // MARK: CodeHighlighter (Shiki running in JavaScriptCore; the bundled
        // highlighter.js is generated by apps/macos/scripts/build-highlighter.mjs)
        .target(
            name: "CodeHighlighter",
            path: "CodeHighlighter/Sources/CodeHighlighter",
            resources: [.copy("Resources/highlighter.js")],
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "CodeHighlighterTests",
            dependencies: ["CodeHighlighter"],
            path: "CodeHighlighter/Tests/CodeHighlighterTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),

        // MARK: CodevisorCore (app logic: models, repositories, DI, view models)
        .target(
            name: "CodevisorCore",
            dependencies: [
                "ACPKit",
                "CodevisorTheming",
                .product(name: "PostHog", package: "posthog-ios")
            ],
            path: "CodevisorCore/Sources/CodevisorCore",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "CodevisorCoreTests",
            dependencies: ["CodevisorCore", "ACPKit"],
            path: "CodevisorCore/Tests/CodevisorCoreTests",
            swiftSettings: [.swiftLanguageMode(.v6)]
        )
    ]
)
