/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellVerifySessionSetupRouteImport } from './routes/_shell/verify.session-setup'
import { Route as ShellVerifyPaneBarRouteImport } from './routes/_shell/verify.pane-bar'
import { Route as ShellVerifyChatParityRouteImport } from './routes/_shell/verify.chat-parity'
import { Route as ShellVerifyChatComposerRouteImport } from './routes/_shell/verify.chat-composer'
import { Route as ShellSessionSessionIdRouteImport } from './routes/_shell/session.$sessionId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVerifySessionSetupRoute = ShellVerifySessionSetupRouteImport.update({
  id: '/verify/session-setup',
  path: '/verify/session-setup',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVerifyPaneBarRoute = ShellVerifyPaneBarRouteImport.update({
  id: '/verify/pane-bar',
  path: '/verify/pane-bar',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVerifyChatParityRoute = ShellVerifyChatParityRouteImport.update({
  id: '/verify/chat-parity',
  path: '/verify/chat-parity',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVerifyChatComposerRoute = ShellVerifyChatComposerRouteImport.update({
  id: '/verify/chat-composer',
  path: '/verify/chat-composer',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSessionSessionIdRoute = ShellSessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/session/$sessionId': typeof ShellSessionSessionIdRoute
  '/verify/chat-composer': typeof ShellVerifyChatComposerRoute
  '/verify/chat-parity': typeof ShellVerifyChatParityRoute
  '/verify/pane-bar': typeof ShellVerifyPaneBarRoute
  '/verify/session-setup': typeof ShellVerifySessionSetupRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/': typeof ShellIndexRoute
  '/session/$sessionId': typeof ShellSessionSessionIdRoute
  '/verify/chat-composer': typeof ShellVerifyChatComposerRoute
  '/verify/chat-parity': typeof ShellVerifyChatParityRoute
  '/verify/pane-bar': typeof ShellVerifyPaneBarRoute
  '/verify/session-setup': typeof ShellVerifySessionSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/session/$sessionId': typeof ShellSessionSessionIdRoute
  '/_shell/verify/chat-composer': typeof ShellVerifyChatComposerRoute
  '/_shell/verify/chat-parity': typeof ShellVerifyChatParityRoute
  '/_shell/verify/pane-bar': typeof ShellVerifyPaneBarRoute
  '/_shell/verify/session-setup': typeof ShellVerifySessionSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/session/$sessionId'
    | '/verify/chat-composer'
    | '/verify/chat-parity'
    | '/verify/pane-bar'
    | '/verify/session-setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/'
    | '/session/$sessionId'
    | '/verify/chat-composer'
    | '/verify/chat-parity'
    | '/verify/pane-bar'
    | '/verify/session-setup'
  id:
    | '__root__'
    | '/_shell'
    | '/onboarding'
    | '/_shell/'
    | '/_shell/session/$sessionId'
    | '/_shell/verify/chat-composer'
    | '/_shell/verify/chat-parity'
    | '/_shell/verify/pane-bar'
    | '/_shell/verify/session-setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/verify/session-setup': {
      id: '/_shell/verify/session-setup'
      path: '/verify/session-setup'
      fullPath: '/verify/session-setup'
      preLoaderRoute: typeof ShellVerifySessionSetupRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/verify/pane-bar': {
      id: '/_shell/verify/pane-bar'
      path: '/verify/pane-bar'
      fullPath: '/verify/pane-bar'
      preLoaderRoute: typeof ShellVerifyPaneBarRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/verify/chat-parity': {
      id: '/_shell/verify/chat-parity'
      path: '/verify/chat-parity'
      fullPath: '/verify/chat-parity'
      preLoaderRoute: typeof ShellVerifyChatParityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/verify/chat-composer': {
      id: '/_shell/verify/chat-composer'
      path: '/verify/chat-composer'
      fullPath: '/verify/chat-composer'
      preLoaderRoute: typeof ShellVerifyChatComposerRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/session/$sessionId': {
      id: '/_shell/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof ShellSessionSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellSessionSessionIdRoute: typeof ShellSessionSessionIdRoute
  ShellVerifyChatComposerRoute: typeof ShellVerifyChatComposerRoute
  ShellVerifyChatParityRoute: typeof ShellVerifyChatParityRoute
  ShellVerifyPaneBarRoute: typeof ShellVerifyPaneBarRoute
  ShellVerifySessionSetupRoute: typeof ShellVerifySessionSetupRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellSessionSessionIdRoute: ShellSessionSessionIdRoute,
  ShellVerifyChatComposerRoute: ShellVerifyChatComposerRoute,
  ShellVerifyChatParityRoute: ShellVerifyChatParityRoute,
  ShellVerifyPaneBarRoute: ShellVerifyPaneBarRoute,
  ShellVerifySessionSetupRoute: ShellVerifySessionSetupRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
