// Renders infra/relays/fly/<id>.toml for every relay in relays.json — one Fly
// app per relay instance, so each has its own stable address
// (docs/plans/codevisor-tunnel.md). The files are checked in for review;
// `--check` fails when they drift from relays.json (CI).
import { readFile, readdir, rm, writeFile } from "node:fs/promises"
import { join } from "node:path"
import process from "node:process"
import { fileURLToPath } from "node:url"

const here = fileURLToPath(new URL(".", import.meta.url))

/// The repository formatter (oxfmt) also formats TOML: it drops indentation
/// and puts one space before inline comments. Emit exactly that, so the
/// committed files pass both this generator's --check and `format:check`.
const formatted = (toml) =>
  toml
    .split("\n")
    .map((line) => line.trimStart().replace(/(\S)\s{2,}#/, "$1 #"))
    .join("\n")

export const flyToml = (relay) => formatted(relayToml(relay))

const relayToml = (relay) => `# Generated by infra/relays/gen-fly.mjs from relays.json. Do not edit.
app = "codevisor-${relay.id}"
primary_region = "${relay.region}"
kill_signal = "SIGTERM"
kill_timeout = 10

[build]
  # Overridden by \`flyctl deploy --image\` in CI with the SHA-tagged image.
  image = "registry.fly.io/codevisor-relay:latest"

[env]
  RELAY_HOSTNAME = "${relay.hostname}"
  RELAY_AUTHORIZE_URL = "https://cloud.codevisor.dev/api/relay/authorize"
  RUST_LOG = "info"

[deploy]
  strategy = "rolling"

# RELAY_AUTHORIZE_TOKEN is a Fly secret, staged by provision.mjs. No DNS or
# ACME credentials live on the relay (certificates use HTTP-01, below).
[mounts]
  source = "relay_data"
  destination = "/data"   # certbot account, webroot, certificate; survives deploys

# QUIC Address Discovery. UDP must use the same internal and external port and
# bind to fly-global-services (resolved in entrypoint.sh). Needs a dedicated IPv4.
[[services]]
  protocol = "udp"
  internal_port = 7842
  auto_stop_machines = "off"
  min_machines_running = 1

  [[services.ports]]
    port = 7842

# Relay over HTTPS/WebSocket. Raw TCP passthrough (no handlers): the relay
# terminates its own TLS, and QUIC reuses the same certificate.
[[services]]
  protocol = "tcp"
  internal_port = 443
  auto_stop_machines = "off"
  min_machines_running = 1

  [[services.ports]]
    port = 443
    handlers = []

  [services.concurrency]
    type = "connections"
    soft_limit = 8000
    hard_limit = 10000

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "60s"

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "120s"
    method = "get"
    path = "/healthz"
    protocol = "https"
    tls_skip_verify = true   # the check dials the Machine's IP, not the hostname

# Plain HTTP, to the port-80 router: Let's Encrypt HTTP-01 challenges, and
# captive-portal probes (/generate_204) forwarded to the relay. No health
# check on purpose: Fly's proxy stops routing to a service whose checks fail,
# and the relay (which /generate_204 reaches) only starts once certbot has
# passed the challenge that must arrive on this port.
[[services]]
  protocol = "tcp"
  internal_port = 80
  auto_stop_machines = "off"
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = []

[metrics]
  port = 9090
  path = "/metrics"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
`

export async function readRelays() {
  return JSON.parse(await readFile(join(here, "relays.json"), "utf8"))
}

async function main(check) {
  const { relays } = await readRelays()
  const flyDir = join(here, "fly")
  const expected = new Map(relays.map((relay) => [`${relay.id}.toml`, flyToml(relay)]))
  const drift = []
  for (const [name, content] of expected) {
    const current = await readFile(join(flyDir, name), "utf8").catch(() => undefined)
    if (current === content) continue
    if (check) drift.push(`${name} is out of date`)
    else await writeFile(join(flyDir, name), content)
  }
  for (const name of await readdir(flyDir)) {
    if (expected.has(name)) continue
    if (check) drift.push(`${name} has no relays.json entry`)
    else await rm(join(flyDir, name))
  }
  if (drift.length > 0) {
    console.error(`infra/relays/fly drifted from relays.json (run node infra/relays/gen-fly.mjs):`)
    for (const line of drift) console.error(`  ${line}`)
    process.exitCode = 1
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await main(process.argv.includes("--check"))
}
