import Foundation
import JavaScriptCore

/// Syntax highlighting via Shiki running inside JavaScriptCore. The bundled
/// `highlighter.js` (generated by apps/macos/scripts/build-highlighter.mjs)
/// carries Shiki's pure-JavaScript regex engine plus a curated grammar set;
/// themes are passed in as raw VSCode/Shiki theme JSON, so any theme the app
/// can load highlights exactly as it would in VSCode.
///
/// An actor: the 2 MB bundle is evaluated lazily on first use, off the main
/// thread, and all JSContext access is serialized. Results are cached per
/// (code, language, theme) — streaming re-renders hit the cache for free.
public actor CodeHighlighter {
    /// One token of highlighted output; `color` is a hex string or nil for
    /// the theme's default foreground.
    public struct Token: Sendable, Equatable, Codable {
        public let content: String
        public let color: String?
    }

    public static let shared = CodeHighlighter()

    private var context: JSContext?
    private var loadFailed = false
    private var cache: [String: [[Token]]] = [:]
    private var cacheOrder: [String] = []
    private let cacheLimit = 200

    public init() {}

    /// Tokenizes `code` under the given theme, or returns nil when the
    /// language is unknown/unsupported or the highlighter can't run (the
    /// caller keeps plain text). `themeKey` must be a stable identity for the
    /// theme JSON (its id) — it keys both caches.
    public func highlight(
        code: String,
        language: String?,
        themeKey: String,
        themeJSON: String
    ) -> [[Token]]? {
        guard let language, !language.isEmpty else { return nil }

        let cacheKey = "\(themeKey)|\(language)|\(code.hashValue)"
        if let cached = cache[cacheKey] { return cached }

        guard let function = highlightFunction() else { return nil }
        let result = function.call(withArguments: [code, language, themeKey, themeJSON])
        guard
            let json = result?.toString(), json != "null",
            let data = json.data(using: .utf8),
            let tokens = try? JSONDecoder().decode([[Token]].self, from: data)
        else { return nil }

        cache[cacheKey] = tokens
        cacheOrder.append(cacheKey)
        if cacheOrder.count > cacheLimit {
            cache.removeValue(forKey: cacheOrder.removeFirst())
        }
        return tokens
    }

    // Evaluates the bundle once and returns the global highlight function.
    // A failed load is remembered so a broken bundle degrades to plain text
    // without retrying on every block.
    private func highlightFunction() -> JSValue? {
        if let context {
            return context.objectForKeyedSubscript("herdmanHighlight")
        }
        guard !loadFailed else { return nil }
        guard
            let url = Bundle.module.url(forResource: "highlighter", withExtension: "js"),
            let source = try? String(contentsOf: url, encoding: .utf8),
            let jsContext = JSContext()
        else {
            loadFailed = true
            return nil
        }
        jsContext.evaluateScript(source)
        let function = jsContext.objectForKeyedSubscript("herdmanHighlight")
        guard let function, !function.isUndefined else {
            loadFailed = true
            return nil
        }
        context = jsContext
        return function
    }
}
