import CodevisorCore
import CodevisorUI
import SwiftUI
import UIKit

// MARK: - Workspace screen

/// A workspace: one full-screen pane (tab) at a time — chats, terminals, and
/// the new-tab page — with a Safari-style grid to switch, add, and close
/// them. The nav bar shows the active pane's title between a sidebar button
/// (back to the workspace list) and the tab-grid button; chat panes hide
/// their title so the transcript scrolls clear off the top.
struct WorkspaceScreen: View {
  @Environment(AppEnvironment.self) var environment
  @Environment(\.dismiss) var dismiss
  @Environment(\.accessibilityReduceMotion) var accessibilityReduceMotion
  @Environment(\.displayScale) var displayScale
  /// The workspace's chat, or nil while the native New Chat sheet owns the
  /// draft composer. Its first send adopts a real session in place; Home then
  /// mounts an ordinary workspace route backed by the same cached controller
  /// before removing the opaque sheet.
  let sessionId: UUID?
  /// Machine identity is part of a session's key. The same server database
  /// can be visible through both a direct/local registration and Codevisor
  /// Cloud, so UUID alone is intentionally insufficient for lookups.
  var serverId: String? = nil
  /// Stable workspace identity for normal routes. Agent rows also supply a
  /// preferred chat; workspace rows leave it nil so the last-open tab wins.
  var workspaceId: UUID? = nil
  var preferredChatSessionId: UUID? = nil
  /// Existing workspaces receive their cached-or-new controller from Home
  /// during destination construction, so the transcript shell is available
  /// on the first frame instead of waiting for this view's async task.
  var initialController: SessionController? = nil
  /// New Chat is hosted by a real system sheet. This flag changes only the
  /// navigation controls; presentation chrome remains system-owned.
  var isNewChatPresentation = false
  /// The first-send overlay is an independently hosted copy of the real
  /// workspace. It temporarily uses the sheet's post-send navigation chrome
  /// while the native modal is removed underneath it.
  var isFirstSendPromotionSurface = false
  /// A one-shot request created when Home begins presenting New Chat. It is
  /// carried to the UIKit editor without being regenerated by view updates.
  var initialComposerFocusRequest: UUID? = nil
  /// Clears the request at its source after UIKit accepts it. Keeping this
  /// acknowledgement above the destination means even an unexpected
  /// composer remount cannot focus the keyboard a second time.
  var onInitialComposerFocusRequestFulfilled: ((UUID) -> Void)? = nil
  /// The first send has minted a real session. HomeView mounts an ordinary
  /// workspace route beneath the sheet.
  var onDraftStarted: ((UUID) -> Void)? = nil
  /// The no-project browser pushes into the sheet's type-erased path. Once a
  /// folder is selected, Home removes only those browser entries.
  /// Home owns the native sheet's Boolean presentation state, so the close
  /// button requests dismissal there. Normal workspace routes keep using
  /// the environment dismiss action.
  var onDismissNewChat: (() -> Void)? = nil
  /// A normal workspace destination reports when its cached transcript has
  /// mounted. Home uses this to remove the opaque sheet without exposing a
  /// spinner or an intermediate navigation frame.
  var onWorkspaceReady: ((UUID) -> Void)? = nil
  /// A destination mounted beneath a promoted New Chat may prepare its
  /// transcript, but the still-visible sheet remains the presentation and
  /// scroll owner until Home commits the handoff.
  var transcriptPresentationRole: TranscriptPresentationRole = .foreground
  var onSendAnimationCompleted: ((UserSendAnimationRequest) -> Void)? = nil
  var onSendAnimationStarted:
    (
      (
        UserSendAnimationRequest,
        TranscriptSendAnimationTarget
      ) -> Bool
    )? = nil
  var onComposerWillSend: ((String, CGRect) -> Void)? = nil
  /// The temporary promotion host supplies UIKit's missing horizontal safe
  /// area so its navigation controls use normal compact-width gutters. The
  /// workspace body ignores only that temporary inset and remains full
  /// width, matching every ordinary chat route.
  var extendsUnderPromotedHorizontalSafeArea = false
  var composerTextEditorHandoffRole: ComposerTextEditorHandoffRole = .none
  var composerTextEditorHandoffID: UUID? = nil

  /// One controller per chat session shown in this workspace (macOS allows
  /// several chats per workspace; so do we).
  @State var controllers: [UUID: SessionController] = [:]
  @State var missing = false
  @State var serverConfig: CodevisorServerConfig?
  @State var project: Project?
  @State var paneState: PaneGroupState?
  /// Set when a draft's first send creates its session. From then on this
  /// screen is that workspace — same view, same pane, same transcript.
  @State var startedSessionId: UUID?
  /// The retained draft controller while `sessionId` is nil.
  @State var draftController: SessionController?
  /// The draft's first send landed: the run pickers collapse away.
  @State var hasStarted = false
  /// Stands in for the session id a draft doesn't have yet, so its pane
  /// group can exist (and keep a STABLE pane id) from the first frame.
  @State var draftPlaceholderId = UUID()
  /// True while `draftController` is the project-less sentinel this screen
  /// minted itself (never the cache's). The moment it points at a real
  /// project, it is swapped for the durable cache-built draft.
  @State var draftIsPlaceholderBorn = false
  /// The tab grid is workspace-local state, not another navigation
  /// destination. Keeping the active pane in Home's NavigationStack means
  /// the system back button and edge swipe always pop straight to Home.
  @State var showsGrid = false
  /// Measured card endpoints for the snapshot-only tab zoom. These are
  /// visual coordinates, never navigation or pane state.
  @State var paneCardFrames: [UUID: CGRect] = [:]
  /// Non-nil only while UIKit owns a native drag session for this card.
  /// Pane order itself always changes through `paneBinding`, so every live
  /// displacement is immediately durable and survives an interrupted drag.
  @State var gridDrag: WorkspaceTabGridDragState?
  @State var suppressedPaneTapId: UUID?
  /// GestureState resets on both normal completion and system cancellation,
  /// giving the lifted card one authoritative release/cleanup signal.
  @GestureState var gridDragGestureIsActive = false
  @State var gridLiftFeedback = 0
  @State var pendingGridZoomPaneId: UUID?
  /// Safari inserts the new tab into the grid first, then expands that
  /// card. Keeping this separate from `pendingGridZoomPaneId` makes the
  /// source of each transition explicit: an existing pane collapses into
  /// the grid, while a newly-created placeholder expands out of it.
  @State var pendingNewTabZoomPaneId: UUID?
  @State var tabZoomSurface: WorkspaceTabZoomSurface?

  /// This workspace's chat: the routed one, or the one a draft's first send
  /// created. Nil only while an unsent draft.
  var activeSessionId: UUID? { sessionId ?? startedSessionId }

  var isDraft: Bool { activeSessionId == nil }

  var resolvedServerId: String {
    serverId ?? draftController?.project.serverId ?? environment.defaultComposerServerId
  }

  var resolvedWorkspace: Workspace? {
    if let workspaceId,
      let workspace = environment.workspaces.loadAll().first(where: {
        $0.serverId == resolvedServerId && $0.id == workspaceId
      })
    {
      return workspace
    }
    guard let activeSessionId else { return nil }
    return environment.workspaces.loadAll().first {
      $0.serverId == resolvedServerId && $0.chatSessionIds.contains(activeSessionId)
    }
  }

  var panes: PaneGroupState {
    if let paneState { return paneState }
    if let workspace = resolvedWorkspace {
      return Self.compactPaneState(from: workspace)
    }
    if let paneStorageId {
      return WorkspacePaneStore.shared.state(
        for: paneStorageId,
        legacySessionIds: legacyPaneSessionIds
      )
    }
    // A draft's pane exists before its session does, keyed by a
    // placeholder so its id — and therefore the chat view's identity —
    // survives the session being adopted.
    return PaneGroupState.centerInitial(sessionId: draftPlaceholderId)
  }

  var activePane: PaneDescriptorState? {
    panes.selectedPane ?? panes.panes.first
  }

  func session(for id: UUID) -> ChatSession? {
    environment.projectList.sessions.first {
      $0.serverId == resolvedServerId && $0.id == id
    }
  }

  var rootSession: ChatSession? { activeSessionId.flatMap(session(for:)) }

  /// The persisted project snapshot is good enough to construct New Chat's
  /// draft immediately. The server refresh that follows may update this
  /// list, but it must not hold the sheet behind a loading surface.
  /// Keep the initial choice on the selected machine, and only a project
  /// the user has used there before: with nothing remembered the draft
  /// starts with no project rather than guessing one.
  var draftProjectCandidate: Project? {
    guard let remembered = environment.composerDefaults.lastProjectId(forServer: resolvedServerId)
    else { return nil }
    return environment.projectList.fleetActiveProjects.first {
      $0.serverId == resolvedServerId && $0.id == remembered && !$0.isScratch
    }
  }

  /// The workspace's project. `prepare()` caches it in state, but it also
  /// resolves synchronously from the already-loaded project list, so the
  /// first frame renders the pane instead of a spinner — arriving from a new
  /// chat's first send must show the chat, not a placeholder.
  var resolvedProject: Project? {
    project
      ?? draftController?.project
      ?? rootSession.flatMap { session in
        environment.projectList.projects.first {
          $0.serverId == session.serverId && $0.id == session.projectId
        }
      }
  }

  /// The app-wide cached controller for a chat, if it already exists — no
  /// creation, so this is safe to call straight from the view body.
  private func cachedController(for chatId: UUID) -> SessionController? {
    guard let session = session(for: chatId) else { return nil }
    return ChatControllerCache.shared.existingController(
      sessionId: chatId,
      serverId: session.serverId
    )
  }

  /// The controller a chat pane shows. A draft's pane is served by the
  /// retained draft controller — the SAME controller the session adopts, so
  /// nothing about the view changes when the send lands.
  func chatController(for pane: PaneDescriptorState) -> SessionController? {
    guard let chatId = pane.chatSessionId ?? activeSessionId else { return draftController }
    if chatId == draftPlaceholderId { return draftController }
    if let controller = controllers[chatId] { return controller }
    if chatId == sessionId, let initialController { return initialController }
    return cachedController(for: chatId)
  }

  func title(for pane: PaneDescriptorState) -> String {
    switch pane.kind {
    case .chat:
      let title =
        (pane.chatSessionId ?? activeSessionId)
        .flatMap(session(for:))?.title ?? pane.name
      return title.isEmpty ? "New Chat" : title
    case .newTab:
      return "New Tab"
    case .terminal, .plugin:
      return pane.name
    }
  }

  var workspaceCwd: String {
    rootSession?.cwd
      ?? resolvedProject?.folderURL.path
      ?? ""
  }

  var body: some View {
    ZStack {
      Color(.systemGroupedBackground)
        .ignoresSafeArea()
      workspaceContent
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
    .modifier(
      PromotedHorizontalSafeAreaExpansion(
        isEnabled: extendsUnderPromotedHorizontalSafeArea
      )
    )
    .allowsHitTesting(
      tabZoomSurface == nil && pendingNewTabZoomPaneId == nil
    )
  }

  private var workspaceContent: some View {
    Group {
      if blocksServerContent {
        let machines = environment.machines
        let machine =
          machines.machine(for: resolvedServerId)
          ?? machines.allMachines.first
          ?? CodevisorMachine.local
        ServerAvailabilityView(
          machineId: machine.id,
          availability: screenAvailability,
          machineName: machine.name,
          isLocal: false
        ) {
          Task {
            await machines.retryMachine(machine.id)
          }
        }
      } else if missing {
        ContentUnavailableView("Chat Not Found", systemImage: "questionmark.bubble")
      } else if isDraft, draftController == nil {
        // Once created, the retained draft controller owns its project.
        // Do not fall back to setup if an older global snapshot briefly
        // omits that project while its server upsert is acknowledged.
        // setUpDraftIfNeeded() runs synchronously at the start of
        // prepare() — with no project anywhere it still mints the
        // sentinel draft, so the composer always renders. Keep the
        // sheet calm for that initial actor turn.
        Color.clear
      } else if resolvedProject == nil {
        DelayedWorkspaceLoadingView()
      } else if preferredChatSessionId != nil, paneState == nil {
        // An agent-row tap is an explicit route. Do not paint the
        // workspace's previously selected terminal/chat while the
        // destination task applies the requested pane.
        DelayedWorkspaceLoadingView()
      } else if showsGrid {
        grid
      } else if let pane = activePane {
        paneContent(pane)
          .id(pane.id)
      } else {
        DelayedWorkspaceLoadingView()
      }
    }
    // Native navigation back to the workspaces list: the system back
    // button and the edge swipe-to-go-back gesture. Hiding the back
    // button for a custom sidebar button disabled the interactive pop.
    // The exception is the tab grid: its back affordance returns to the
    // last-open tab, because the grid is workspace-local navigation.
    .navigationBarBackButtonHidden(showsGrid)
    .navigationTitle(baseTitle)
    .navigationBarTitleDisplayMode(.inline)
    .toolbar {
      WorkspaceScreenToolbar(
        showsGrid: showsGrid,
        isNewChatPresentation: isNewChatPresentation,
        hasStarted: hasStarted,
        isFirstSendPromotionSurface: isFirstSendPromotionSurface,
        blocksServerContent: blocksServerContent,
        isDraft: isDraft,
        onReopenSelectedPane: { reopenSelectedPane() },
        onDismissNewChat: { dismissNewChatPresentation() },
        onAddTab: { addTab() },
        onShowGrid: {
          if let pane = activePane { showGrid(from: pane) }
        }
      )
    }
    .task(id: screenAvailability) {
      guard case .ready = screenAvailability else { return }
      await prepare()
    }
    .task(id: panePreviewLoadToken) {
      guard let paneStorageId else { return }
      await PaneSnapshotCache.shared.loadPersistedPreviews(
        workspaceId: paneStorageId,
        paneIds: panes.panes.map(\.id)
      )
    }
    .onChange(of: screenAvailability) { _, availability in
      if case .ready = availability { return }
      showsGrid = false
    }
    .onChange(of: environment.projectList.projects.map(\.id)) { _, _ in
      setUpDraftIfNeeded()
    }
    // The chip's picker retargets the sentinel at a real project in
    // place; swap it for the durable cache-built draft (same text). A
    // first send re-points the sentinel at its scratch folder instead —
    // that controller is mid-send and must stay mounted.
    .onChange(of: draftController?.project.id) { _, _ in
      guard draftIsPlaceholderBorn,
        let sentinel = draftController,
        !sentinel.project.isRunTargetPlaceholder,
        !sentinel.project.isScratch,
        !sentinel.isSubmitting,
        !sentinel.hasAcceptedFirstSend
      else { return }
      setUpDraftIfNeeded(preferredProject: sentinel.project)
    }
    // A machine's harness catalog changed (sign-in, enablement, a
    // ferried credential landing): refresh a mounted draft composer so
    // new harnesses and models appear without reopening the screen.
    .onChange(of: environment.harnessCatalogRevision(for: resolvedServerId)) { _, _ in
      guard let draftController, isDraft else { return }
      draftController.invalidateHarnessCapabilities()
      Task { await draftController.refreshHarnessCapabilities() }
    }
    .onChange(of: environment.workspaceSync.revision) { _, _ in
      synchronizePaneStateFromWorkspace()
    }
    .iosNavigationDiagnostics(navigationDiagnosticState)
  }

  /// THIS screen's machine, not the app's selected one: a workspace can
  /// belong to any machine in the fleet (a chat sent to another machine's
  /// project), and the selected machine's hiccups must never block it —
  /// nor may its content wait on the wrong machine becoming ready.
  private var screenAvailability: ServerAvailability {
    environment.machines.availabilityByMachineId[resolvedServerId] ?? .ready
  }

  private var blocksServerContent: Bool {
    if case .ready = screenAvailability {
      return false
    }
    return true
  }

  private var navigationDiagnosticState: IOSNavigationDiagnosticState {
    let identifier = workspaceId ?? activeSessionId ?? draftPlaceholderId
    let contentPhase: String
    if blocksServerContent {
      contentPhase = "server-blocked"
    } else if isDraft {
      contentPhase = draftController == nil ? "draft-missing" : "draft-ready"
    } else if let pane = activePane, pane.kind == .chat {
      if let controller = chatController(for: pane) {
        if controller.model != nil {
          contentPhase = "model-ready"
        } else if controller.isConnecting {
          contentPhase = "connecting"
        } else if controller.isLoadingInitialHistory {
          contentPhase = "history-loading-idle"
        } else {
          contentPhase = "model-missing-idle"
        }
      } else {
        contentPhase = "controller-missing"
      }
    } else {
      contentPhase = "non-chat"
    }
    return IOSNavigationDiagnosticState(
      screen: "workspace",
      identifier: String(identifier.uuidString.prefix(8)),
      showsGrid: showsGrid,
      isNewChatPresentation: isNewChatPresentation,
      hasStarted: hasStarted,
      isDraft: isDraft,
      blocksServerContent: blocksServerContent,
      expectsNativeBack: !isNewChatPresentation && !showsGrid,
      expectsLeadingButton: (showsGrid && !isNewChatPresentation)
        || (isNewChatPresentation
          && (hasStarted || isFirstSendPromotionSurface)),
      expectsTrailingButton: (isNewChatPresentation && !hasStarted)
        || (!blocksServerContent && !isDraft),
      contentPhase: contentPhase
    )
  }

  /// The draft's first surface when its machine has no usable project.
  /// This is the real file picker, hosted by the sheet's navigation stack.
  private var baseTitle: String {
    // An unsent draft says what it is; the moment it becomes a real chat the
    // title clears like any other chat pane, so the nav bar doesn't change
    // shape under the send.
    if isDraft { return hasStarted ? "" : "New Chat" }
    if showsGrid {
      return "\(panes.panes.count) Tab\(panes.panes.count == 1 ? "" : "s")"
    }
    guard let pane = activePane else { return "" }
    // Chat panes hide the title so the transcript scrolls off the top.
    return pane.kind == .chat ? "" : title(for: pane)
  }
}
