import type { Context } from "hono"
import { html } from "hono/html"
import { isDevAuthEnabled, type CloudEnv } from "../env.js"
import { CLOUD_VERSION } from "../version.js"
// Generated by `bun run build:css`; bundled as a text module (wrangler rules)
// and inlined so the Worker serves fully self-contained pages.
import styles from "../generated/styles.css"

type Ctx = Context<{ Bindings: CloudEnv }>

/// These five pages are the entire human-facing web surface of the cloud
/// instance — deliberately server-rendered, framework-free, and tiny. All
/// machine/session management UI lives in the native apps.

const page = (c: Ctx, title: string, body: unknown, script?: string) =>
  c.html(
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="noindex" />
        <title>{`${title} · ${c.env.INSTANCE_NAME}`}</title>
        <style dangerouslySetInnerHTML={{ __html: styles }} />
      </head>
      <body class="min-h-screen bg-zinc-950 font-sans text-zinc-100 antialiased">
        <main class="mx-auto flex min-h-screen w-full max-w-md flex-col justify-center gap-6 px-6 py-16">
          <header class="flex items-baseline justify-between">
            <span class="text-sm font-semibold tracking-wide text-zinc-400">
              {c.env.INSTANCE_NAME}
            </span>
            <span class="font-mono text-xs text-zinc-600">v{CLOUD_VERSION}</span>
          </header>
          <section class="rounded-2xl border border-zinc-800 bg-zinc-900 p-8 shadow-xl">
            {body}
          </section>
          <footer class="text-center text-xs text-zinc-600">
            Codevisor Cloud · end-to-end encrypted relay
          </footer>
        </main>
        {script !== undefined
          ? html`<script>
              ${html([script] as unknown as TemplateStringsArray)}
            </script>`
          : null}
      </body>
    </html>
  )

const heading = (title: string, subtitle?: string) => (
  <div class="mb-6">
    <h1 class="text-xl font-semibold">{title}</h1>
    {subtitle !== undefined ? (
      <p class="mt-2 text-sm leading-relaxed text-zinc-400">{subtitle}</p>
    ) : null}
  </div>
)

// -- / ------------------------------------------------------------------------

export const homePage = (c: Ctx) =>
  page(
    c,
    "Cloud",
    <>
      {heading(
        "This is a Codevisor Cloud instance",
        "It connects your Codevisor apps to your machines through an end-to-end encrypted relay. There's nothing to do here — sign in from the Codevisor app, or run `codevisor auth login` on a machine."
      )}
      <a class="text-sm text-sky-400 hover:text-sky-300" href="https://codevisor.dev/docs">
        Codevisor documentation →
      </a>
    </>
  )

// -- /login -------------------------------------------------------------------

export const loginPage = (c: Ctx) => {
  const hasGithub = c.env.GITHUB_CLIENT_ID !== undefined
  const dev = isDevAuthEnabled(c.env)
  return page(
    c,
    "Sign in",
    <>
      {heading("Sign in", "Authenticate to continue.")}
      <div class="flex flex-col gap-3">
        {hasGithub ? (
          <button
            id="github"
            class="w-full rounded-lg bg-zinc-100 px-4 py-2.5 text-sm font-medium text-zinc-900 hover:bg-white"
          >
            Continue with GitHub
          </button>
        ) : (
          <p class="text-sm text-zinc-500">No sign-in providers are configured on this instance.</p>
        )}
        {dev ? (
          <a
            class="w-full rounded-lg border border-amber-500/40 px-4 py-2.5 text-center text-sm font-medium text-amber-400 hover:bg-amber-500/10"
            href={`/dev-login${location(c)}`}
          >
            Continue as Dev User
          </a>
        ) : null}
      </div>
    </>,
    `
    const redirect = new URLSearchParams(location.search).get("redirect") ?? "/";
    document.getElementById("github")?.addEventListener("click", async () => {
      const res = await fetch("/api/auth/sign-in/social", {
        method: "POST",
        headers: { "content-type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ provider: "github", callbackURL: redirect })
      });
      const data = await res.json();
      if (data.url) location.href = data.url;
    });
    `
  )
}

const location = (c: Ctx): string => {
  const redirect = c.req.query("redirect")
  return redirect !== undefined ? `?redirect=${encodeURIComponent(redirect)}` : ""
}

// -- /dev-login ---------------------------------------------------------------

export const devLoginPage = (c: Ctx) => {
  if (!isDevAuthEnabled(c.env)) return c.notFound()
  return page(
    c,
    "Dev sign in",
    <>
      {heading("Dev sign in", "Signing you in as the local development user…")}
      <p id="status" class="text-sm text-zinc-400">
        Working…
      </p>
    </>,
    `
    const redirect = new URLSearchParams(location.search).get("redirect") ?? "/";
    fetch("/dev/login", { method: "POST", credentials: "include" })
      .then((res) => {
        if (!res.ok) throw new Error("dev login failed");
        location.href = redirect;
      })
      .catch(() => { document.getElementById("status").textContent = "Dev login failed."; });
    `
  )
}

// -- /device ------------------------------------------------------------------

export const devicePage = (c: Ctx) =>
  page(
    c,
    "Connect a machine",
    <>
      {heading(
        "Connect a machine",
        "A machine running `codevisor auth login` showed you a code. Confirm it below to connect that machine to your account."
      )}
      <div id="signin" class="hidden">
        <p class="mb-4 text-sm text-zinc-400">You need to sign in first.</p>
        <a
          id="signin-link"
          class="block w-full rounded-lg bg-zinc-100 px-4 py-2.5 text-center text-sm font-medium text-zinc-900 hover:bg-white"
          href="/login"
        >
          Sign in to continue
        </a>
      </div>
      <form id="form" class="hidden flex-col gap-4">
        <input
          id="code"
          class="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3 text-center font-mono text-lg tracking-[0.3em] uppercase placeholder:tracking-normal placeholder:text-zinc-600"
          placeholder="Enter code"
          autocomplete="off"
          spellcheck={false}
        />
        <p class="text-xs leading-relaxed text-amber-400/90">
          Only approve codes you requested yourself, moments ago, on a machine you own. Anyone with
          an approved code can access your machines.
        </p>
        <div class="flex gap-3">
          <button
            id="approve"
            type="submit"
            class="flex-1 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-emerald-950 hover:bg-emerald-400"
          >
            Connect machine
          </button>
          <button
            id="deny"
            type="button"
            class="flex-1 rounded-lg border border-zinc-700 px-4 py-2.5 text-sm font-medium text-zinc-300 hover:bg-zinc-800"
          >
            Deny
          </button>
        </div>
      </form>
      <p id="result" class="hidden text-sm"></p>
    </>,
    `
    const qs = new URLSearchParams(location.search);
    const codeInput = document.getElementById("code");
    codeInput.value = qs.get("user_code") ?? "";
    const show = (id) => {
      for (const el of ["signin", "form", "result"]) document.getElementById(el).classList.add("hidden");
      const el = document.getElementById(id);
      el.classList.remove("hidden");
      if (id === "form") el.classList.add("flex");
    };
    const finish = (message, ok) => {
      const result = document.getElementById("result");
      result.textContent = message;
      result.className = "text-sm " + (ok ? "text-emerald-400" : "text-red-400");
      show("result");
    };
    fetch("/api/auth/get-session", { credentials: "include" })
      .then((res) => res.json())
      .then((session) => {
        if (!session || !session.user) {
          document.getElementById("signin-link").href =
            "/login?redirect=" + encodeURIComponent(location.pathname + location.search);
          show("signin");
        } else {
          show("form");
        }
      });
    const act = async (path) => {
      const userCode = codeInput.value.trim().replace(/-/g, "");
      if (!userCode) return;
      // Claim the code for this verifying session before acting on it.
      await fetch("/api/auth/device?user_code=" + encodeURIComponent(userCode), {
        credentials: "include"
      });
      const res = await fetch("/api/auth/device/" + path, {
        method: "POST",
        headers: { "content-type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ userCode })
      });
      if (res.ok) {
        finish(path === "approve"
          ? "Machine connected. You can return to your terminal — it will finish up on its own."
          : "Request denied.", path === "approve");
      } else {
        const data = await res.json().catch(() => ({}));
        finish(data.message ?? "That code wasn't recognized. Codes expire after a few minutes.", false);
      }
    };
    document.getElementById("form").addEventListener("submit", (event) => { event.preventDefault(); act("approve"); });
    document.getElementById("deny").addEventListener("click", () => act("deny"));
    `
  )

// -- /auth/handoff ------------------------------------------------------------

export const handoffPage = (c: Ctx) =>
  page(
    c,
    "Signed in",
    <>
      {heading("Signed in")}
      <p id="status" class="text-sm leading-relaxed text-zinc-400">
        Finishing up…
      </p>
    </>,
    `
    const done = (message) => { document.getElementById("status").textContent = message; };
    const scheme = new URLSearchParams(location.search).get("app");
    // Only ever hand sessions to the Codevisor apps' registered URL schemes
    // (codevisor-dev is the development build's scheme).
    if (scheme !== null && scheme !== "codevisor" && scheme !== "codevisor-dev") {
      done("Unrecognized app link.");
    } else {
      fetch("/api/auth/get-session", { credentials: "include" })
        .then((res) => res.json())
        .then(async (session) => {
          if (!session || !session.user) { done("Sign-in didn't complete. Close this tab and try again."); return; }
          if (scheme === null) { done("You're signed in. You can close this tab."); return; }
          const res = await fetch("/api/auth/one-time-token/generate", {
            credentials: "include"
          });
          const data = await res.json();
          location.href = scheme + "://cloud-auth?ott=" + encodeURIComponent(data.token);
          done("You're signed in — returning to Codevisor. You can close this tab.");
        })
        .catch(() => done("Something went wrong. Close this tab and try again."));
    }
    `
  )
