import { randomUUID } from "node:crypto"

// Compact, single-word food slugs for automatically named production worktrees.
// The broad vocabulary keeps names varied while remaining easy to read in paths,
// branch names, and window titles.
const produceNames = [
  "ackee",
  "acorn",
  "alfalfa",
  "allium",
  "amla",
  "apple",
  "apricot",
  "artichoke",
  "arugula",
  "asparagus",
  "avocado",
  "babaco",
  "bamboo",
  "banana",
  "beet",
  "beetroot",
  "bilberry",
  "blackberry",
  "blackcurrant",
  "blueberry",
  "bokchoy",
  "boysenberry",
  "breadfruit",
  "broccoli",
  "broccolini",
  "burdock",
  "cabbage",
  "calabash",
  "cantaloupe",
  "caper",
  "carambola",
  "carrot",
  "cassava",
  "cauliflower",
  "celeriac",
  "celery",
  "chard",
  "cherimoya",
  "cherry",
  "chestnut",
  "chicory",
  "chive",
  "clementine",
  "cloudberry",
  "coconut",
  "collard",
  "corn",
  "courgette",
  "cranberry",
  "cucumber",
  "currant",
  "daikon",
  "damson",
  "date",
  "dewberry",
  "dragonfruit",
  "durian",
  "elderberry",
  "endive",
  "feijoa",
  "fennel",
  "fig",
  "garlic",
  "gooseberry",
  "grape",
  "grapefruit",
  "greengage",
  "guava",
  "honeyberry",
  "honeydew",
  "horseradish",
  "huckleberry",
  "jackfruit",
  "jalapeno",
  "jicama",
  "kale",
  "kohlrabi",
  "kumquat",
  "leek",
  "lemon",
  "lettuce",
  "lime",
  "lingonberry",
  "longan",
  "loquat",
  "lychee",
  "mandarin",
  "mango",
  "mangosteen",
  "melon",
  "mulberry",
  "mushroom",
  "nectarine",
  "okra",
  "olive",
  "onion",
  "orange",
  "papaya",
  "parsnip",
  "passionfruit",
  "pawpaw",
  "peach",
  "pear",
  "persimmon",
  "physalis",
  "pineapple",
  "plantain",
  "plum",
  "pomegranate",
  "pomelo",
  "potato",
  "pumpkin",
  "quince",
  "radicchio",
  "radish",
  "rambutan",
  "raspberry",
  "rhubarb",
  "rutabaga",
  "salsify",
  "scallion",
  "shallot",
  "spinach",
  "squash",
  "starfruit",
  "strawberry",
  "sunchoke",
  "swede",
  "tamarillo",
  "tamarind",
  "tangerine",
  "taro",
  "tomatillo",
  "tomato",
  "turnip",
  "watercress",
  "watermelon",
  "yam",
  "yuzu",
  "zucchini"
] as const

const grainNutNames = [
  "adzuki",
  "almond",
  "amaranth",
  "barley",
  "bean",
  "buckwheat",
  "bulgur",
  "cashew",
  "chickpea",
  "cowpea",
  "einkorn",
  "emmer",
  "farro",
  "flaxseed",
  "freekeh",
  "hazelnut",
  "hempseed",
  "hominy",
  "kamut",
  "kasha",
  "lentil",
  "macadamia",
  "maize",
  "millet",
  "mungbean",
  "oat",
  "peanut",
  "pecan",
  "pepita",
  "pistachio",
  "popcorn",
  "quinoa",
  "rice",
  "rye",
  "sesame",
  "sorghum",
  "soybean",
  "spelt",
  "teff",
  "triticale",
  "walnut",
  "wheat",
  "wildrice"
] as const

const herbSpiceNames = [
  "ajwain",
  "allspice",
  "angelica",
  "anise",
  "annatto",
  "asafoetida",
  "basil",
  "bergamot",
  "borage",
  "caraway",
  "cardamom",
  "cassia",
  "cayenne",
  "chervil",
  "cilantro",
  "cinnamon",
  "clove",
  "coriander",
  "cumin",
  "curcuma",
  "dill",
  "epazote",
  "fenugreek",
  "galangal",
  "ginger",
  "hyssop",
  "juniper",
  "lavender",
  "lemongrass",
  "licorice",
  "mace",
  "marjoram",
  "mint",
  "mugwort",
  "mustard",
  "nigella",
  "nutmeg",
  "oregano",
  "paprika",
  "parsley",
  "pepper",
  "peppermint",
  "perilla",
  "rosemary",
  "saffron",
  "sage",
  "savory",
  "shiso",
  "sorrel",
  "spearmint",
  "sumac",
  "tarragon",
  "thyme",
  "turmeric",
  "vanilla",
  "wasabi",
  "zaatar"
] as const

const dairyNames = [
  "asiago",
  "brie",
  "butter",
  "buttermilk",
  "camembert",
  "cheddar",
  "cheese",
  "chevre",
  "colby",
  "cream",
  "edam",
  "emmental",
  "feta",
  "fontina",
  "ghee",
  "gouda",
  "gruyere",
  "halloumi",
  "havarti",
  "kefir",
  "labneh",
  "manchego",
  "mascarpone",
  "milk",
  "mozzarella",
  "muenster",
  "paneer",
  "parmesan",
  "pecorino",
  "provolone",
  "quark",
  "raclette",
  "ricotta",
  "romano",
  "roquefort",
  "skyr",
  "stilton",
  "taleggio",
  "yogurt"
] as const

const proteinNames = [
  "abalone",
  "anchovy",
  "bass",
  "beef",
  "bison",
  "bonito",
  "brisket",
  "buffalo",
  "calamari",
  "capon",
  "carp",
  "catfish",
  "caviar",
  "char",
  "chicken",
  "clam",
  "cockle",
  "cod",
  "conch",
  "crab",
  "crayfish",
  "cuttlefish",
  "duck",
  "eel",
  "egg",
  "elk",
  "emu",
  "flounder",
  "goat",
  "grouper",
  "haddock",
  "hake",
  "halibut",
  "ham",
  "herring",
  "kangaroo",
  "lamb",
  "lobster",
  "mackerel",
  "marlin",
  "mussel",
  "mutton",
  "octopus",
  "oyster",
  "perch",
  "pheasant",
  "pollock",
  "pork",
  "prawn",
  "quail",
  "rabbit",
  "salmon",
  "sardine",
  "scallop",
  "shrimp",
  "smelt",
  "snail",
  "snapper",
  "sole",
  "squid",
  "sturgeon",
  "swordfish",
  "tilapia",
  "trout",
  "tuna",
  "turkey",
  "veal",
  "venison",
  "whitefish",
  "whelk"
] as const

const dishNames = [
  "arepa",
  "aspic",
  "bagel",
  "baguette",
  "baklava",
  "bao",
  "barbecue",
  "biryani",
  "biscotti",
  "biscuit",
  "blini",
  "borscht",
  "bread",
  "brioche",
  "brownie",
  "burrito",
  "cannoli",
  "carbonara",
  "casserole",
  "ceviche",
  "challah",
  "chapati",
  "chowder",
  "churro",
  "cobbler",
  "congee",
  "cookie",
  "couscous",
  "cracker",
  "crepe",
  "croissant",
  "crumpet",
  "cupcake",
  "curry",
  "dal",
  "dimsum",
  "dolma",
  "doughnut",
  "dumpling",
  "eclair",
  "empanada",
  "enchilada",
  "falafel",
  "focaccia",
  "fondue",
  "frittata",
  "gazpacho",
  "gnocchi",
  "granola",
  "gratin",
  "grits",
  "gumbo",
  "gyoza",
  "haggis",
  "halvah",
  "hamburger",
  "hotdog",
  "hummus",
  "idli",
  "jambalaya",
  "jerky",
  "kebab",
  "kimchi",
  "knish",
  "kugel",
  "lasagna",
  "macaroni",
  "meatball",
  "meatloaf",
  "moussaka",
  "muffin",
  "naan",
  "nachos",
  "noodles",
  "omelet",
  "paella",
  "pancake",
  "panini",
  "pasta",
  "pasty",
  "pho",
  "pierogi",
  "pilaf",
  "pizza",
  "porridge",
  "pretzel",
  "quesadilla",
  "ramen",
  "ravioli",
  "risotto",
  "roti",
  "samosa",
  "sandwich",
  "satay",
  "sauerkraut",
  "sausage",
  "schnitzel",
  "scone",
  "shawarma",
  "souffle",
  "spaghetti",
  "strudel",
  "sushi",
  "taco",
  "tamale",
  "tempura",
  "terrine",
  "toast",
  "tostada",
  "tortilla",
  "waffle",
  "wonton",
  "ziti"
] as const

const sweetNames = [
  "affogato",
  "ambrosia",
  "bonbon",
  "brittle",
  "butterscotch",
  "candy",
  "caramel",
  "cheesecake",
  "chiffon",
  "chocolate",
  "clafoutis",
  "cocoa",
  "compote",
  "custard",
  "flan",
  "fudge",
  "ganache",
  "gelato",
  "gummies",
  "macaroon",
  "marshmallow",
  "marzipan",
  "meringue",
  "mousse",
  "nougat",
  "parfait",
  "praline",
  "pudding",
  "shortbread",
  "sherbet",
  "sorbet",
  "sundae",
  "tiramisu",
  "toffee",
  "trifle",
  "truffle"
] as const

const pantryNames = [
  "agave",
  "aioli",
  "balsamic",
  "broth",
  "chutney",
  "consomme",
  "dashi",
  "dressing",
  "gelatin",
  "gravy",
  "honey",
  "jam",
  "jelly",
  "ketchup",
  "marmalade",
  "mayo",
  "mayonnaise",
  "molasses",
  "nectar",
  "oil",
  "pesto",
  "pickle",
  "relish",
  "salsa",
  "salt",
  "sauce",
  "stock",
  "syrup",
  "tahini",
  "vinegar"
] as const

const drinkNames = [
  "ale",
  "beer",
  "cider",
  "coffee",
  "espresso",
  "horchata",
  "juice",
  "kombucha",
  "lager",
  "lemonade",
  "mead",
  "milkshake",
  "mocha",
  "punch",
  "smoothie",
  "soda",
  "tea",
  "tisane",
  "toddy"
] as const

export const productionFoodWorktreeNames: ReadonlyArray<string> = [
  ...produceNames,
  ...grainNutNames,
  ...herbSpiceNames,
  ...dairyNames,
  ...proteinNames,
  ...dishNames,
  ...sweetNames,
  ...pantryNames,
  ...drinkNames
]

const randomNameAttempts = 20
const randomIdAttempts = 20

const randomNameIndex = (random: () => number): number =>
  Math.min(
    productionFoodWorktreeNames.length - 1,
    Math.floor(random() * productionFoodWorktreeNames.length)
  )

const randomNameAt = (random: () => number): string =>
  productionFoodWorktreeNames[randomNameIndex(random)]!

const defaultRandomId = (): string => randomUUID().replaceAll("-", "").slice(0, 8)

/// Tries inexpensive random picks first, then scans the complete food pool from
/// a random offset. A random ID is appended only when every base name is in use.
export const availableProductionWorktreeName = (
  existing: ReadonlySet<string>,
  random: () => number = Math.random,
  randomId: () => string = defaultRandomId
): string => {
  for (let attempt = 0; attempt < randomNameAttempts; attempt += 1) {
    const candidate = randomNameAt(random)
    if (!existing.has(candidate)) {
      return candidate
    }
  }

  const startIndex = randomNameIndex(random)
  for (let offset = 0; offset < productionFoodWorktreeNames.length; offset += 1) {
    const index = (startIndex + offset) % productionFoodWorktreeNames.length
    const candidate = productionFoodWorktreeNames[index]!
    if (!existing.has(candidate)) {
      return candidate
    }
  }

  const base = randomNameAt(random)
  for (let attempt = 0; attempt < randomIdAttempts; attempt += 1) {
    const candidate = `${base}-${randomId()}`
    if (!existing.has(candidate)) {
      return candidate
    }
  }
  throw new Error("Unable to allocate a unique production worktree name")
}
